### ISSUE TITLE
buildImageFromDockerfile returning `Right ()` when server reports error: invalid reference format

### ISSUE THREAD

**Issue by locallycompact** [denibertovic/docker-hs#39] opened 2017-10-24 13:48 UTC
Hi, I have pushed this error to the repository [here](https://gitlab.com/locallycompact/FullMetalHaskell/tree/lc/invalid_reference_format) at branch lc/invalid_reference_format. Clone recursively.

The code is in the Shakefile, use `stack exec shake dockers` to observe the error. The getDockerVersion call works, whilst the buildImageFromDockerfile returns `Right ()` but does not execute a build and in the log I see

    ERRO[2017-10-24T14:40:40.606285141+01:00] Handler for POST /v1.24/build returned error: invalid reference format

**Comment by jprider63** [comment] 2017-10-27 18:01
I haven't used this functionality and didn't write this code, so @denibertovic might know more. 

It looks like docker still [returns 200 even if there is an error](https://docs.docker.com/engine/api/v1.24/#32-images). It looks like docker also returns multiple json statuses in the response body. 

The solution to this might be to switch to `requestHelper` instead of `requestUnit` in `buildImageFromDockerfile`. Then we can take the last line of the body and return unit if it isn't a JSON error.

**Comment by jprider63** [comment] 2017-10-27 18:08
What does this endpoint return on success? Should we return a `ContainerID` instead of `()`?

**Comment by denibertovic** [comment] 2017-11-01 11:31
@locallycompact Thanks to @jprider63 and @SKoschnicke this should work now. At least I can't reproduce it anymore. I've also added an integration test that tests this endpoint. Please verify that it works for you and I'll cut a new release. (Thanks for reporting)

**Comment by denibertovic** [comment] 2017-11-01 11:32
@jprider63 To answer your question about what this endpoint returns....it's basically a streaming endpoint of logs while the image is building.... Last time I checked anyway

**Comment by denibertovic** [comment] 2017-11-15 12:55
I'm gonna close this since  we have a test case for it and it passes. Feel free to re-open if something is still not working.

**Closed by denibertovic** 2017-11-15 12:55 UTC
